### ISSUE TITLE
timeToLive and expireTime params - How they works?

### ISSUE THREAD

**Issue by GiboMac** [rcs-business-messaging/rbm-api-examples#2]
Hello!

I wanted to know if and how the parameters are used.

I cloned the repo locally and tested send and check capabilities.

I then wanted to try setting a ttl and, in another case expireTime, but nothing seems to change from a message perspective.

To test the ttl I did so:
```
- put the phone offline
- set '1s' of ttl
- send message
- waited 5s
- turned phone on
- message received correctly
```

To test the expireTime I did this way:
```
- put the phone offline
- set the expireTime to a time in the past
- sent message
- turned the phone on
- message received correctly
```

Did I do something wrong? 

Thank you very much for your help

**Comment by ianbuckner** [comment]
These are a new feature that are currently only available to a small number of early access partners where the feature has been enabled on a per-agent basis. This is why you wont find any public documentation yet and also why the feature wont work unless you are part of the EAP.

Basically, this feature means that a developer can set how long an undelivered RBM message shoudl remain in the RBM platform. This simplifies a developers code as they do not need to run timers and use the _revoke_ function.

**Comment by ianbuckner** [comment]
Please note that this feature has now been rolled out live into production and is available to all developers. Se our [Release Notes](https://developers.google.com/business-communications/rcs-business-messaging/guides/release-notes#november_29_2023) for details.

**Comment by GiboMac** [comment]
Thank you @ianbuckner for the update!
