### ISSUE TITLE
C# Examples

### ISSUE THREAD

**Issue by mskilton** [rcs-business-messaging/rbm-api-examples#5]
The docs mention this REPO for C# examples but don't see any.  Are they missing?

**Comment by ianbuckner** [comment]
They were but we added them a few days ago: https://github.com/rcs-business-messaging/rbm-api-examples/tree/master/csharp. We have updated things and will be adding a further example shortly.

**Comment by ianbuckner** [comment]
Additional demo added: https://github.com/rcs-business-messaging/rbm-api-examples/tree/master/csharp/agents/rbm-csharp-kitchen-sink

**Comment by ianbuckner** [comment]
Marking as complete.
